update configure script, and check -laudit HAVE_LIBAUDIT, if available

diff --git a/sepgsql/configure b/sepgsql/configure
--- a/sepgsql/configure
+++ b/sepgsql/configure
@@ -710,7 +710,7 @@ with_libxml
 with_libxslt
 with_system_tzdata
 with_zlib
-enable_selinux
+SELINUX_LIBS
 GREP
 EGREP
 ELF_SYS
@@ -5563,6 +5563,7 @@ fi
 
 
 if test "$enable_selinux" = yes; then
+    SELINUX_LIBS="-lselinux"
     { echo "$as_me:$LINENO: checking for avc_netlink_loop in -lselinux" >&5
 echo $ECHO_N "checking for avc_netlink_loop in -lselinux... $ECHO_C" >&6; }
 if test "${ac_cv_lib_selinux_avc_netlink_loop+set}" = set; then
@@ -5630,12 +5631,81 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_SELINUX 1
 _ACEOF
 
-
 else
   { { echo "$as_me:$LINENO: error: \"--enable-selinux requires libselinux.\"" >&5
 echo "$as_me: error: \"--enable-selinux requires libselinux.\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+    { echo "$as_me:$LINENO: checking for audit_open in -laudit" >&5
+echo $ECHO_N "checking for audit_open in -laudit... $ECHO_C" >&6; }
+if test "${ac_cv_lib_audit_audit_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-laudit  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char audit_open ();
+int
+main ()
+{
+return audit_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_audit_audit_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_audit_audit_open=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_audit_audit_open" >&5
+echo "${ECHO_T}$ac_cv_lib_audit_audit_open" >&6; }
+if test $ac_cv_lib_audit_audit_open = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBAUDIT 1
+_ACEOF
+
+                 SELINUX_LIBS="$SELINUX_LIBS -laudit"
+fi
+
 
 fi
 
@@ -28245,7 +28315,7 @@ with_libxml!$with_libxml$ac_delim
 with_libxslt!$with_libxslt$ac_delim
 with_system_tzdata!$with_system_tzdata$ac_delim
 with_zlib!$with_zlib$ac_delim
-enable_selinux!$enable_selinux$ac_delim
+SELINUX_LIBS!$SELINUX_LIBS$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 ELF_SYS!$ELF_SYS$ac_delim
