- modify object id of procedures - fix test cases

diff --git a/sepgsql/src/test/sepgsql/Makefile b/sepgsql/src/test/sepgsql/Makefile
--- a/sepgsql/src/test/sepgsql/Makefile
+++ b/sepgsql/src/test/sepgsql/Makefile
@@ -22,7 +22,7 @@ launch_psql: launch_psql.c
 
 results.diff: $(TESTCASES:sql/%.sql=results/%.diff)
 	@for x in $^; do cat $$x >> $@; done
-	@test -s $@ && echo "HINT: See $@ to confirm errors" || :
+	@test -s $@ && echo "HINT: See $(shell pwd)/$@ to confirm errors" || :
 
 results/%.diff: sql/%.sql
 	@./launch_psql $(PSQL) -a $(DBNAME) < $< >& $(@:%.diff=%.out)
@@ -49,9 +49,9 @@ check:
 	@$(PSQL) -qt -c 'SHOW sepostgresql' -d $(DBNAME) 2>/dev/null | grep -q on || \
 		(echo "HINT: database \"$(DBNAME)\" is not available"; \
 		 echo "HINT: SE-PostgreSQL may not be available on server"; exit 1)
-	@$(GETSEBOOL) allow_user_postgresql_connect | grep -q 'on$' || \
+	@$(GETSEBOOL) allow_user_postgresql_connect | grep -q 'on$$' || \
 		(echo "HINT: check allow_user_postgresql_connect boolean"; exit 1)
-	@$(GETSEBOOL) sepgsql_regression_test_mode | grep -q 'on$' || \
+	@$(GETSEBOOL) sepgsql_regression_test_mode | grep -q 'on$$' || \
 		(echo "HINT: check sepgsql_regression_test_mode boolean"; \
 		 echo "HINT: check sepostgresql-devel.pp installed"; exit 1)
 	@$(RUNCON) -t sepgsql_test_t -l s0-s0:c0.c15 \
@@ -59,9 +59,4 @@ check:
 		(echo "HINT: /sbin/restorecon -R <prefix> and restart"; \
 		 echo "HINT: user shell should have 's0-s0:c0.c15' range, at least"; \
 		 echo "      semanage enables to set up it"; exit 1)
-	@if test -x /etc/init.d/mcstrans; then			\
-		/etc/init.d/mcstrans status >& /dev/null &&	\
-		(echo "HINT: stop mcstrans daemon"; exit 1) ||	\
-		(test $$? -eq 3 && exit 0 || exit 1)		\
-	fi
 	@echo "PASS: check runtime environment"
