update sepgsql testcases framework

diff --git a/sepgsql/src/test/sepgsql/Makefile b/sepgsql/src/test/sepgsql/Makefile
--- a/sepgsql/src/test/sepgsql/Makefile
+++ b/sepgsql/src/test/sepgsql/Makefile
@@ -1,29 +1,37 @@
-PSQL	:= $(shell which psql)
-RUNCON	:= $(shell which runcon)
-DBNAME	:= test
+# ----------------------------------------------------
+# Makefile for SE-PostgreSQL testcases
+# ----------------------------------------------------
+PSQL      := $(shell which psql)
+DIFF      := $(shell which diff)
+RUNCON    := $(shell which runcon)
+GETSEBOOL := $(shell which getsebool)
+DBNAME	  := test
 
-RUN_DBA  = $(RUNCON) unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c15 $(PSQL) -aq $(DBNAME)
-RUN_USER = $(RUNCON) unconfined_u:unconfined_r:sepgsql_test_t:s0-s0:c0   $(PSQL) -aq $(DBNAME)
+TESTCASES = $(wildcard sql/*.sql)
 
-TESTCASES = $(notdir $(wildcard sql/*.sql))
+test: init check setup results.diff
 
-test: clean run_test
+init:
+	rm -f results.diff results/*.out results/*.diff
 
-clean:
-	@rm -f whole_results.diff results/*.out results/*.diff
+clean: init
+	rm -f launch_psql
 
-run_test: environment filesystem $(TESTCASES:.sql=.test)
+launch_psql: launch_psql.c
+	$(CC) $< -o $@ -lselinux
 
-%.test: sql/%.sql
-	@touch results/$*.out
-	@test -r sql/$*.init && $(RUN_DBA) -f sql/$*.init >> results/$*.out 2>&1 || :
-	@$(RUN_USER) -f sql/$*.sql >> results/$*.out 2>&1 || :
-	@test -r sql/$*.fini && $(RUN_DBA) -f sql/$*.fini >> results/$*.out 2>&1 || :
-	@diff -u expected/$*.out results/$*.out > results/$*.diff 2>/dev/null && echo -n "PASS: " || echo -n "FAIL: "
-	@echo $@
-	@cat results/$*.diff >> whole_results.diff
+results.diff: $(TESTCASES:sql/%.sql=results/%.diff)
+	@for x in $^; do cat $$x >> $@; done
+	@test -s $@ && echo "HINT: See $@ to confirm errors" || :
 
-filesystem:
+results/%.diff: sql/%.sql
+	@./launch_psql $(PSQL) -a $(DBNAME) < $< >& $(@:%.diff=%.out)
+	@$(DIFF) -u $(<:sql/%.sql=expected/%.out)	\
+	            $(<:sql/%.sql=results/%.out) >& $@	\
+		&& echo -n "PASS: " || echo -n "FAIL: "
+	@echo $(notdir $(@:.diff=))
+
+setup: launch_psql
 	@test -e /tmp/sepgsql_test_copy_1 && rm -f /tmp/sepgsql_test_copy_1 || :
 	@test -e /tmp/sepgsql_test_copy_2 && rm -f /tmp/sepgsql_test_copy_2 || :
 	@test -e /tmp/sepgsql_test_blob && rm -f /tmp/sepgsql_test_blob || :
@@ -32,25 +40,25 @@ filesystem:
 	@chcon -t postgresql_db_t  -l s0 /tmp/sepgsql_test_copy_1
 	@chcon -t postgresql_tmp_t -l s0 /tmp/sepgsql_test_copy_2
 	@chcon -t postgresql_tmp_t -l s0 /tmp/sepgsql_test_blob
+	@echo "PASS: setup filesystem objects"
 
-environment:
-	@test -x $(PSQL) || (echo "$(PSQL) is not available"; exit 1)
-	@test -x $(RUNCON) || (echo "$(RUNCON) is not available"; exit 1)
-	@$(PSQL) -qt -c '' -d $(DBNAME) || \
-		(echo "HINT: connection to $(DBNAME) is not available"; exit 1)
+check:
+	@test -x $(PSQL) || \
+		(echo "HINT: $(PSQL) is not available"; exit 1)
 	@$(PSQL) -qt -c 'SHOW pgace_feature' -d $(DBNAME) | grep -q selinux || \
-		(echo "HINT: daemon is not SE-PostgreSQL"; exit 1)
-	@/usr/sbin/selinuxenabled || \
-		(echo "HINT: SELinux is disabled!"; exit 1)
-	@$(RUNCON) -t sepgsql_test_t -l s0-s0:c0.c15 id -Z > /dev/null || \
-		(echo "HINT: install sepostgresql-devel.pp"; exit 1)
-	@$(RUN_DBA) -c 'SELECT sepgsql_getcon()' >& /dev/null || \
-		(echo "HINT: do /sbin/restorecon -R and restart"; exit 1)
-	@$(RUN_USER) -c 'SELECT sepgsql_getcon()' >& /dev/null || \
-		(echo "HINT: do /sbin/restorecon -R and restart"; \
-		 echo "HINT: do /usr/sbin/setsebool -P allow_user_postgresql_connect=1"; \
-		 exit 1)
-	@/etc/init.d/mcstrans status > /dev/null && \
-		(echo "HINT: stop 'mcstrans' daemon!"; exit 1) || \
+		(echo "HINT: database $(PSQL) is not available"; \
+		 echo "HINT: SE-PostgreSQL is not available on server"; exit 1)
+	@$(GETSEBOOL) allow_user_postgresql_connect | grep -q on || \
+		(echo "HINT: check allow_user_postgresql_connect boolean"; exit 1)
+	@$(GETSEBOOL) sepgsql_regression_test_mode | grep -q on || \
+		(echo "HINT: check sepgsql_regression_test_mode boolean"; \
+		 echo "HINT: check sepostgresql-devel.pp installed"; exit 1)
+	@$(RUNCON) -t sepgsql_test_t -l s0-s0:c0.c15 \
+		$(PSQL) -c 'SELECT sepgsql_getcon()' $(DBNAME) >& /dev/null || \
+		(echo "HINT: /sbin/restorecon -R <prefix> and restart"; \
+		 echo "HINT: user shell should have 's0-s0:c0.c15' range, at least" \
+		 echo "      semanage enables to set up it"; exit 1)
+	@test -x /etc/init.d/mcstrans && /etc/init.d/mcstrans status >& /dev/null && \
+		(echo "HINT: stop mcstrans daemon"; exit 1) || \
 		(test $$? -eq 3 && exit 0 || exit 1)
-	@echo "PASS: platform environment for the test"
+	@echo "PASS: check runtime environment"
